Russian translation
ganymedes01/TheErebus pull request #767
Opened 2020-04-10 14:48 UTC by Blueberryy

2020-04-17 10:05 UTC, Blueberryy commented
Merge please.

2020-05-28 18:11 UTC, Blueberryy commented
@Smollet777  Review my changes.

2020-05-29 17:46 UTC, Smollet777 requested changes

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +advancement.erebus.agriculture.bamboo.desc=Получите в свои руки некоторые Колоссальные Бамбуковые и Колоссальные Бамбуковые Побеги.
Получите Колоссальный бамбук и Колоссальные Бамбуковые Побеги.

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +item.erebus.materials.scorpion_pincer.name=Жало скорпиона
"Клешня"

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +item.erebus.materials.resin.name=Древестная смола
"Древесная"

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +item.erebus.smoothie.givin_me_the_blues.name=Смузи дающий мне блюз
Это отсылка к песне, а та, в свою очередь - игра слов с устоявшимся выражением.
https://forum.wordreference.com/threads/give-the-blues.1654832/
Изменять или нет я хз, но "дающий мне" звучит неоч

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +tile.erebus.wall_amber.name=Янтарные ограда
Янтарн**ая**

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +tile.erebus.temple_brick.name=Карпич храма
Кирпич

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +tooltip.erebus.wandofpreservation=Стреляет янтарными звездами и захватывает мобов. Шелк касается блока, чтобы собрать или сломать, чтобы освободить толпу.
Шелковым касанием соберите блок или сломайте, чтобы освободить толпу.

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +key.erebus.beetleram=Атаковать жуком-рам
Таран жуком

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +advancement.erebus.exploration.arborist=Навязчивый лесовод
Кому навязывается? Деревьям? "Одержимый лесовод"

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +advancement.erebus.exploration.find_beetles.desc=Имейте несколько встречу встречу с любым из жуков или их личинками.
Переживите немного нехорошее столкновение с любым из жуков или их личинками.
Очередной каламбур, на этот раз с Битлз. Как же я обожаю переводить каламбуры =_=

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +advancement.erebus.exploration.beetlejuice.desc=Подоите жука, чтобы получить сок жука, аналог Erebus к молоку.
аналог молока в Erebus

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +advancement.erebus.exploration.poison_sac.desc=Получите яд саквояж из внутренностей одного из многих ядовитых тварей, населяющих Erebus.
Получите мешочек яда

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +advancement.erebus.exploration.repellent.desc=Возьми в руки немного репеллента.
Добудьте немного репеллента.

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +advancement.erebus.exploration.whetstone.desc=Возьмите в руки немного Порошка точильного камня и примените его к незачарованному Точильному камню.
"Добудьте Порошка"
"Get your hands on" не переводится дословно. "Заполучите", "достаньте", "добудьте"... Есть куча синонимов

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +tile.erebus.honey_comb.name=Медовая бомба
Тут " honey comb" (Медовые соты) не "honey bomb"

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +advancement.erebus.agriculture.honeycomb.desc=Построить медовую момбу.
Собрать медовые соты

2020-05-29 17:46 UTC, Smollet777 commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +advancement.erebus.agriculture.beetle_breed.desc=Приведите двух Жуков в настроение, кормя их самыми эротичными овощами - по крайней мере, по ним мы не судим.
Приведите двух Жуков в надлежащее настроение, кормя их самым эротичным из овощей. Для них, по крайней мере. Не нам судить.

2020-05-31 09:10 UTC, Blueberryy commented on src/main/resources/assets/erebus/lang/ru_ru.lang
> +advancement.erebus.agriculture.beetle_breed.desc=Приведите двух Жуков в настроение, кормя их самыми эротичными овощами - по крайней мере, по ним мы не судим.
Thanks

2020-06-02 10:34 UTC, Smollet777 approved these changes

2025-04-07 04:03 UTC, closed without merging